title: CodeV Log # the title of your blog

subtitle: CodeV 개발자들의 팀 블로그 # subtitle of your blog

description: >- # this means to ignore newlines until "baseurl:"
  개발 고민, 알게된 것, 공유하고 싶은 것들을 정리하고 공개합니다 :)

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# All the images can be found at - /_site/assets/img/

author_logo: profile.png  # your profile image 

disqus_shortname: your-disqus-username   #for comments using disqus

# Author details

author: CodeV
author_bio: Hello, we are CodeV team. 개발자들을 위한 정리 서비스를 만들고 있습니다. 
author_email: ""
author_location: South Korea
author_website_url: "https://github.com/codevlog"

# social links 



# important to use devlopr theme 
theme: devlopr