# Setup
title:        CodeV Log
tagline:      CodeV 개발자들의 팀 블로그. 개발 고민, 알게된 것, 공유하고 싶은 것들을 정리하고 공개합니다 :)
baseurl:      ""
paginate:     1
locale:       "ko"

# About/contact
author:
  name:       CodeV Team
  url:        http://github.com/codevlog

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown