title: CodeV Log
description: CodeV 개발자들의 팀 블로그. 개발 고민, 알게된 것, 공유하고 싶은 것들을 정리하고 공개합니다 :)
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

github:
  repository_url: https://github.com/codevlog.github.io